### ISSUE TITLE
Unison Prompt

### ISSUE THREAD

**Issue by phreed** [concord-consortium/docker-volume-sync#5]
While running the docker compose I get a prompt for a `unison` password.
Any password satisfies the prompt.
What is causing this?

```
docker compose -f docker-compose-jg-corpus.yaml run --rm sync
```
```yaml
version: '3'
services:
  sync:
    image: concordconsortium/docker-volume-sync
    volumes:
      - type: volume
        source: 'jg-corpus-data'
        target: /data
      - type: bind
        source: ./build/download
        target: /host_data
  app:
    build:
      context: .
    entrypoint: ["/bin/bash", "/usr/local/bin/wait-for-it.sh", "sync:5001", "-s", "-t", "30", "--"]
    command: ["echo", "jg-corpus-data is synchronized"]
    depends_on: [ sync ]

volumes:
  jg-corpus-data: { external: true }
```
The output looks like the following.
```
Changing password for unison
New password:
Bad password: too weak
Retype password:
passwd: password for unison changed by root
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Warning: No archive files were found for these roots, whose canonical names are:
        /host_data
        /data
This can happen either
because this is the first time you have synchronized these roots,
or because you have upgraded Unison to a new version with a different
archive format.

Update detection may take a while on this run if the replicas are
large.

Unison will assume that the 'last synchronized state' of both replicas
was completely empty.  This means that any files that are different
will be reported as conflicts, and any files that exist only on one
replica will be judged as new and propagated to the other replica.
If the two replicas are identical, then no changes will be reported.

If you see this message repeatedly, it may be because one of your machines
is getting its address from DHCP, which is causing its host name to change
between synchronizations.  See the documentation for the UNISONLOCALHOSTNAME
environment variable for advice on how to correct this.

Donations to the Unison project are gratefully accepted:
http://www.cis.upenn.edu/~bcpierce/unison

Reconciling changes
file     ---->            ensample.graphml
Propagating updates
UNISON 2.51.2 (OCAML 4.06.1) started propagating changes at 20:54:59.19 on 19 Oct 2021
[BGN] Copying ensample.graphml from /host_data to /data
[END] Copying ensample.graphml
UNISON 2.51.2 (OCAML 4.06.1) finished propagating changes at 20:54:59.19 on 19 Oct 2021
Saving synchronizer state
Synchronization complete at 20:54:59  (1 item transferred, 0 skipped, 0 failed)
Initial sync complete, opening port 5001 to let the world know
Unison 2.51.2 (ocaml 4.06.1): Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
```
